default_language_version:
  python: python

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: update-init-files
        name: Update __init__.py files
        entry: python scripts/update_init.py --all
        language: system
        pass_filenames: false
        always_run: true
      - id: generate-url-docs
        name: Generate URL documentation
        entry: python scripts/generate_url_docs.py
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
