name: Django CI

on:
  push:
    branches: ["main", "timesheet-overview"]  # Branches monitoradas
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_msm_workflow
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install Dependencies
      run: |
        poetry install

    - name: Configure MySQL Authentication
      run: |
        docker exec $(docker ps -q --filter ancestor=mysql:5.7) mysql -u root -ppassword -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'password'; FLUSH PRIVILEGES;"

    - name: Wait for MySQL
      run: |
        timeout=300  # Timeout de 5 minutos
        elapsed=0
        while ! mysqladmin ping -h "localhost" -u root -ppassword --silent; do
          if [ "$elapsed" -ge "$timeout" ]; then
            echo "Timeout waiting for MySQL"
            exit 1
          fi
          echo "Waiting for database connection..."
          sleep 2
          elapsed=$((elapsed+2))
        done

    - name: Debug MySQL Connection
      run: |
        echo "Testing MySQL Connection"
        mysqladmin ping -h localhost -u root -ppassword

    - name: Run Tests
      env:
        MYSQL_DATABASE: "msm_workflow"
        MSM_DB_USER: root
        DB_PASSWORD: password
        DB_HOST: "localhost"
        DB_PORT: 3306
      run: |
        poetry run python manage.py test

    - name: Get MySQL Logs (on error)
      if: failure()
      run: |
        docker logs $(docker ps -q --filter ancestor=mysql:5.7)
