name: Django CI

on:
  push:
    branches: ["main", "timesheet-overview"]  # Branches monitoradas
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test_msm_workflow
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -ppassword --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=30
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry

    - name: Install Dependencies
      run: |
        poetry install

    - name: Prepare Database
      run: |
        docker exec $(docker ps -q --filter ancestor=mysql:8.0) mysql -u root -ppassword -e "DROP DATABASE IF EXISTS test_msm_workflow; CREATE DATABASE test_msm_workflow;"

    - name: Run Tests
      env:
        MYSQL_DATABASE: "${{ secrets.MYSQL_DATABASE }}"
        MSM_DB_USER: "${{ secrets.MSM_DB_USER }}"
        DB_PASSWORD: "${{ secrets.DB_PASSWORD }}"
        DB_HOST: "${{ secrets.DB_HOST }}"
        DB_PORT: "${{ secrets.DB_PORT }}"
        DEBUG: "True"
      run: |
        poetry run python manage.py test --verbosity 2 --keepdb

    - name: Get MySQL Logs (on error)
      if: failure()
      run: |
        docker logs $(docker ps -q --filter ancestor=mysql:8.0)

    - name: Get Detailed MySQL Logs
      if: failure()
      run: |
        docker exec $(docker ps -q --filter ancestor=mysql:8.0) cat /var/log/mysql/error.log
