name: Django CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      # Code Checkout
      - name: Checkout Repository
        uses: actions/checkout@v4

      # SSH Configuration and EC2 Deploy
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Application to EC2
        env:
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ${{ secrets.AWS_USER }}
        run: |
          ssh -T -o StrictHostKeyChecking=no $AWS_USER@$AWS_HOST << 'EOF'
            cd ${{ secrets.PROJECT_PATH }}
            git pull -f origin main

            source venv/bin/activate

            poetry install
            npm install

            python manage.py migrate
            python manage.py collectstatic --noinput

            sudo systemctl restart gunicorn
            sudo systemctl reload nginx
          EOF

      # Completion Notification
      - name: Notify Deployment Success
        run: echo "✅ Deployment to AWS EC2 completed successfully!"
