name: Django CI

on:
  push:
    branches: [ "main", "timesheet-overview" ] # Just testing new configs
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test_msm_workflow
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=20s
          --health-timeout=10s
          --health-retries=5
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install Dependencies
      run: |
        poetry install
    - name: Wait for MySQL
      run: |
        timeout=300  # 5 minutes timeout
        elapsed=0
        while ! mysqladmin ping -h "localhost" -u root -ppassword --silent; do
          if [ "$elapsed" -ge "$timeout" ]; then
            echo "Timeout waiting for MySQL"
            exit 1
          fi
          echo "Waiting for database connection..."
          sleep 2
          elapsed=$((elapsed+2))
        done
    - name: Run Tests
      env:
        MYSQL_DATABASE: "msm_workflow"
        MSM_DB_USER: root
        DB_PASSWORD: password
        DB_HOST: "localhost"
        DB_PORT: 3306
      run: |
        poetry run python manage.py test
        
